try {
    alert('start of try runs');
    lalala;
    alert('end of try')
} catch (err) {
    alert("error has occured!");
    console.log(err);
}

